releases:

# ArgoCD Deployment

  - name: argocd-{{ .Environment.Name }}
    chart: ../helm/charts/argocd
    namespace: agrocd-{{ .Environment.Name }}
    version: 4.9.8
    values:
      - overrides/argocd/argocd.yaml.gotmpl
      - overrides/argocd/configs/configs.yaml.gotmpl
      - overrides/argocd/repoServer/repoServer.yaml.gotmpl
      - overrides/argocd/server/server.yaml.gotmpl
      - overrides/argocd/controller/controller.yaml.gotmpl
    labels:
        tier: frontend
        app: argocd
    wait: false
    installed: true
    force: false
  
  - name: argocd-redis-{{ .Environment.Name }}
    chart: ../helm/charts/argocd/redis-ha
    namespace: agrocd-{{ .Environment.Name }}
    version: 4.16.0
    values:
      - overrides/argocd/redis/redis.yaml.gotmpl
    labels:
        tier: backend
        app: argocd
    wait: false
    installed: true
    force: false
  
  - name: argocd-image-updater-{{ .Environment.Name }}
    chart: ../helm/charts/argocd/image-updater
    namespace: agrocd-{{ .Environment.Name }}
    version: 0.8.0
    values:
      - overrides/argocd/image-updater/image-updater.yaml.gotmpl
    labels:
        tier: image-updater
        app: argocd
    wait: false
    installed: true
    force: false
  


    
