---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: agrocd-meganrd2
spec:
  project: default
  source:
    repoURL: 'https://github.com/bitnami/charts.git'
    path: bitnami/kube-prometheus
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true