# Default values for teamcity.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.  
replicaCount: 1

secrets:
  enabled: false
  image: mtscontainers.azurecr.io/azurekvsidecar:latest

persistence:
  storageClass: dtsstorageclass

istio:
  ssl:
    enabled: false

extraEnv:
  - name: TEAMCITY_HTTPS_PROXY_ENABLED
    value: "true"
port:
  enabled: true
  name: http
  port: 8111
  protocol: TCP

image:
  repository: jetbrains/teamcity-server
  tag: 2021.2.3
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8111

ingress:
  enabled: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

networkPolicy:
  enabled: false
  ingressCidrBlock: 10.100.1.0/24
  egressPodMatchLabels:
    app: database

livenessProbe:
  enabled: false
  delay: 30
  path: /

readinessProbe:
  enabled: false
  delay: 30
  path: /

nameOverride: ""
fullnameOverride: ""
image:
  repository: jetbrains/teamcity-server
  tag: 2022.04.1
  pullPolicy: Always

rbac:
  readSecrets: true
service:
  port: 80
  targetPort: 8111
ingress:
  enabled: true
  tls:
    - hosts:
        - teamcity.{{ requiredEnv "BASE_DOMAIN" }}
      secretName: dev-admin-wc-tls
  hosts:
    - teamcity.{{ requiredEnv "BASE_DOMAIN" }}
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"


persistence:
    enabled: true
    size: 32Gi
    mounts: 
      - mountPath: "/var/run/docker.sock"
        name: dockersock
    volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
    storageClass: dtsstorageclass
nameOverride: dts-teamcity
global:
  postgresql:
    servicePort: 5432


