---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: agrocd-meganrd2
spec:
  project: default
  source:
    repoURL: 'https://github.com/hashicorp/vault-helm.git'
    path: .
    targetRevision: HEAD
    helm:
      passCredentials: false # If true then adds --pass-credentials to Helm commands to pass credentials to all domains
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      parameters: 
      - name: BASE_DOMAIN
        value: $BASE_DOMAIN
      values: |
        server:
          ingress:
              enabled: true
              ingressClassName: nginx
              annotations: {}
                  # kubernetes.io/ingress.class: nginx
                  # kubernetes.io/tls-acme: "true"
              hosts:
                  - host: "vault-agro.${BASE_DOMAIN}"
                    paths: []
              tls: 
                - secretName: dev-admin-wc-tls
                  hosts:
                    - "vault.${BASE_DOMAIN}"
          dataStorage:
              storageClass: dtsstorageclass
          auditStorage:
              enabled: true
              storageClass: dtsstorageclass
          ha:
              enabled: true
              replicas: 2
              raft:
                  enabled: true
      
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false
