{{ if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: teamcity-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
{{ if .Values.istio.ssl.enabled }}    
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ .Values.istio.ssl.certificateSecretName }}
{{ else }}
  - port:
      number: 80
      name: http
      protocol: HTTP
{{ end }}      
    hosts:
    {{- range .Values.istio.hosts }}
    - {{ . }}
    {{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: teamcity-virtualsvc
spec:
  hosts:
  - "*"
  gateways:
  - teamcity-gateway
  http:
    - name: teamcity-http
      route:
      - destination:
          host: {{ .Chart.Name }}-service
          port:
            number: {{ .Values.service.port }}             
{{ end }}